=begin
#Shared API

#Convictional is the first B2B trade enablement network. This API allows developers to build on our seller and buyer capabilities. This API is unstable, meaning the endpoints could be added, updated or removed without notice. We intend to make backwards incompatible changes in the future, and will make best efforts to notify you in the event of your usage of impacted endpoints. If you plan to build on this API, please contact us for recommendations via support@convictional.com.

The version of the OpenAPI document: v2021-01-01
Contact: support@convictional.com
Generated by: https://openapi-generator.tech
OpenAPI Generator version: 5.3.1

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for ConvictionalShared::SFTPUserDeleteSuccessData
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe ConvictionalShared::SFTPUserDeleteSuccessData do
  let(:instance) { ConvictionalShared::SFTPUserDeleteSuccessData.new }

  describe 'test an instance of SFTPUserDeleteSuccessData' do
    it 'should create an instance of SFTPUserDeleteSuccessData' do
      expect(instance).to be_instance_of(ConvictionalShared::SFTPUserDeleteSuccessData)
    end
  end
  describe 'test attribute "status"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
