=begin
#Shared API

#Convictional is the first B2B trade enablement network. This API allows developers to build on our seller and buyer capabilities. This API is unstable, meaning the endpoints could be added, updated or removed without notice. We intend to make backwards incompatible changes in the future, and will make best efforts to notify you in the event of your usage of impacted endpoints. If you plan to build on this API, please contact us for recommendations via support@convictional.com.

The version of the OpenAPI document: v2021-01-01
Contact: support@convictional.com
Generated by: https://openapi-generator.tech
OpenAPI Generator version: 5.3.1

=end

# Common files
require 'convictional_shared/api_client'
require 'convictional_shared/api_error'
require 'convictional_shared/version'
require 'convictional_shared/configuration'

# Models
require 'convictional_shared/models/auth_me'
require 'convictional_shared/models/company'
require 'convictional_shared/models/document'
require 'convictional_shared/models/document_company_viewers'
require 'convictional_shared/models/empty_error'
require 'convictional_shared/models/error_message'
require 'convictional_shared/models/get_document'
require 'convictional_shared/models/getting_started'
require 'convictional_shared/models/inline_response200'
require 'convictional_shared/models/inline_response400'
require 'convictional_shared/models/inline_response401'
require 'convictional_shared/models/inline_response404'
require 'convictional_shared/models/inline_response500'
require 'convictional_shared/models/inline_response5001'
require 'convictional_shared/models/onboarding_state'
require 'convictional_shared/models/onboarding_user_request'
require 'convictional_shared/models/partner'
require 'convictional_shared/models/partner_create'
require 'convictional_shared/models/partner_update'
require 'convictional_shared/models/response_meta_data'
require 'convictional_shared/models/sftp_user_create_success'
require 'convictional_shared/models/sftp_user_create_success_data'
require 'convictional_shared/models/sftp_user_creds'
require 'convictional_shared/models/sftp_user_delete_success'
require 'convictional_shared/models/sftp_user_delete_success_data'
require 'convictional_shared/models/sftp_user_update'
require 'convictional_shared/models/sftp_user_update_success'
require 'convictional_shared/models/sftp_user_update_success_data'
require 'convictional_shared/models/upload_document'
require 'convictional_shared/models/upload_document_partners_with_view_access'
require 'convictional_shared/models/user'
require 'convictional_shared/models/user_create'
require 'convictional_shared/models/user_update'

# APIs
require 'convictional_shared/api/company_api'
require 'convictional_shared/api/document_api'
require 'convictional_shared/api/partner_api'
require 'convictional_shared/api/user_api'

module ConvictionalShared
  class << self
    # Customize default settings for the SDK using block.
    #   ConvictionalShared.configure do |config|
    #     config.username = "xxx"
    #     config.password = "xxx"
    #   end
    # If no block given, return the default Configuration object.
    def configure
      if block_given?
        yield(Configuration.default)
      else
        Configuration.default
      end
    end
  end
end
