=begin
#Shared API

#Convictional is the first B2B trade enablement network. This API allows developers to build on our seller and buyer capabilities. This API is unstable, meaning the endpoints could be added, updated or removed without notice. We intend to make backwards incompatible changes in the future, and will make best efforts to notify you in the event of your usage of impacted endpoints. If you plan to build on this API, please contact us for recommendations via support@convictional.com.

The version of the OpenAPI document: v2021-01-01
Contact: support@convictional.com
Generated by: https://openapi-generator.tech
OpenAPI Generator version: 5.3.1

=end

require 'date'
require 'time'

module ConvictionalShared
  class Partner
    # The ID of the partner.
    attr_accessor :_id

    # ID of the price list assigned to this customer.
    attr_accessor :pricing_id

    # The timestamp of creation.
    attr_accessor :created

    # The timestamp of last update.
    attr_accessor :updated

    # The ID of the seller company.
    attr_accessor :seller_company_object_id

    # The ID of the buyer company.
    attr_accessor :buyer_company_object_id

    # The average time in hours it takes the seller to ship an order, based on a given time period. Default is last 30 days.
    attr_accessor :average_ship_time

    # The percentage of returned orders over the given time period. Default is last 30 days. Value between 0 and 1.
    attr_accessor :average_return_rate

    # Assigned to the buyer or partnership by the seller.
    attr_accessor :seller_assigned_code

    # Assigned to the seller or partnership by the buyer.
    attr_accessor :buyer_assigned_code

    # The name of the seller company associated with this partner. Only populated when called by a buyer.
    attr_accessor :seller_name

    # The name of the buyer company associated with this partner. Only populated when called by a seller.
    attr_accessor :buyer_name

    attr_accessor :metafields

    # The seller has completed all onboarding steps onto Convictional.
    attr_accessor :seller_onboarding_completed

    # The buyer has completed all onboarding steps onto Convictional.
    attr_accessor :buyer_onboarding_completed

    attr_accessor :getting_started

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'_id' => :'_id',
        :'pricing_id' => :'pricingId',
        :'created' => :'created',
        :'updated' => :'updated',
        :'seller_company_object_id' => :'sellerCompanyObjectId',
        :'buyer_company_object_id' => :'buyerCompanyObjectId',
        :'average_ship_time' => :'averageShipTime',
        :'average_return_rate' => :'averageReturnRate',
        :'seller_assigned_code' => :'sellerAssignedCode',
        :'buyer_assigned_code' => :'buyerAssignedCode',
        :'seller_name' => :'sellerName',
        :'buyer_name' => :'buyerName',
        :'metafields' => :'metafields',
        :'seller_onboarding_completed' => :'sellerOnboardingCompleted',
        :'buyer_onboarding_completed' => :'buyerOnboardingCompleted',
        :'getting_started' => :'gettingStarted'
      }
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'_id' => :'String',
        :'pricing_id' => :'String',
        :'created' => :'String',
        :'updated' => :'String',
        :'seller_company_object_id' => :'String',
        :'buyer_company_object_id' => :'String',
        :'average_ship_time' => :'Float',
        :'average_return_rate' => :'Float',
        :'seller_assigned_code' => :'String',
        :'buyer_assigned_code' => :'String',
        :'seller_name' => :'String',
        :'buyer_name' => :'String',
        :'metafields' => :'Hash<String, Hash<String, Object>>',
        :'seller_onboarding_completed' => :'Boolean',
        :'buyer_onboarding_completed' => :'Boolean',
        :'getting_started' => :'GettingStarted'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `ConvictionalShared::Partner` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!self.class.attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `ConvictionalShared::Partner`. Please check the name to make sure it's valid. List of attributes: " + self.class.attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'_id')
        self._id = attributes[:'_id']
      end

      if attributes.key?(:'pricing_id')
        self.pricing_id = attributes[:'pricing_id']
      end

      if attributes.key?(:'created')
        self.created = attributes[:'created']
      end

      if attributes.key?(:'updated')
        self.updated = attributes[:'updated']
      end

      if attributes.key?(:'seller_company_object_id')
        self.seller_company_object_id = attributes[:'seller_company_object_id']
      end

      if attributes.key?(:'buyer_company_object_id')
        self.buyer_company_object_id = attributes[:'buyer_company_object_id']
      end

      if attributes.key?(:'average_ship_time')
        self.average_ship_time = attributes[:'average_ship_time']
      end

      if attributes.key?(:'average_return_rate')
        self.average_return_rate = attributes[:'average_return_rate']
      end

      if attributes.key?(:'seller_assigned_code')
        self.seller_assigned_code = attributes[:'seller_assigned_code']
      end

      if attributes.key?(:'buyer_assigned_code')
        self.buyer_assigned_code = attributes[:'buyer_assigned_code']
      end

      if attributes.key?(:'seller_name')
        self.seller_name = attributes[:'seller_name']
      end

      if attributes.key?(:'buyer_name')
        self.buyer_name = attributes[:'buyer_name']
      end

      if attributes.key?(:'metafields')
        if (value = attributes[:'metafields']).is_a?(Hash)
          self.metafields = value
        end
      end

      if attributes.key?(:'seller_onboarding_completed')
        self.seller_onboarding_completed = attributes[:'seller_onboarding_completed']
      end

      if attributes.key?(:'buyer_onboarding_completed')
        self.buyer_onboarding_completed = attributes[:'buyer_onboarding_completed']
      end

      if attributes.key?(:'getting_started')
        self.getting_started = attributes[:'getting_started']
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      invalid_properties = Array.new
      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      true
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          _id == o._id &&
          pricing_id == o.pricing_id &&
          created == o.created &&
          updated == o.updated &&
          seller_company_object_id == o.seller_company_object_id &&
          buyer_company_object_id == o.buyer_company_object_id &&
          average_ship_time == o.average_ship_time &&
          average_return_rate == o.average_return_rate &&
          seller_assigned_code == o.seller_assigned_code &&
          buyer_assigned_code == o.buyer_assigned_code &&
          seller_name == o.seller_name &&
          buyer_name == o.buyer_name &&
          metafields == o.metafields &&
          seller_onboarding_completed == o.seller_onboarding_completed &&
          buyer_onboarding_completed == o.buyer_onboarding_completed &&
          getting_started == o.getting_started
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [_id, pricing_id, created, updated, seller_company_object_id, buyer_company_object_id, average_ship_time, average_return_rate, seller_assigned_code, buyer_assigned_code, seller_name, buyer_name, metafields, seller_onboarding_completed, buyer_onboarding_completed, getting_started].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      new.build_from_hash(attributes)
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      self.class.openapi_types.each_pair do |key, type|
        if attributes[self.class.attribute_map[key]].nil? && self.class.openapi_nullable.include?(key)
          self.send("#{key}=", nil)
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[self.class.attribute_map[key]].is_a?(Array)
            self.send("#{key}=", attributes[self.class.attribute_map[key]].map { |v| _deserialize($1, v) })
          end
        elsif !attributes[self.class.attribute_map[key]].nil?
          self.send("#{key}=", _deserialize(type, attributes[self.class.attribute_map[key]]))
        end
      end

      self
    end

    # Deserializes the data based on type
    # @param string type Data type
    # @param string value Value to be deserialized
    # @return [Object] Deserialized data
    def _deserialize(type, value)
      case type.to_sym
      when :Time
        Time.parse(value)
      when :Date
        Date.parse(value)
      when :String
        value.to_s
      when :Integer
        value.to_i
      when :Float
        value.to_f
      when :Boolean
        if value.to_s =~ /\A(true|t|yes|y|1)\z/i
          true
        else
          false
        end
      when :Object
        # generic object (usually a Hash), return directly
        value
      when /\AArray<(?<inner_type>.+)>\z/
        inner_type = Regexp.last_match[:inner_type]
        value.map { |v| _deserialize(inner_type, v) }
      when /\AHash<(?<k_type>.+?), (?<v_type>.+)>\z/
        k_type = Regexp.last_match[:k_type]
        v_type = Regexp.last_match[:v_type]
        {}.tap do |hash|
          value.each do |k, v|
            hash[_deserialize(k_type, k)] = _deserialize(v_type, v)
          end
        end
      else # model
        # models (e.g. Pet) or oneOf
        klass = ConvictionalShared.const_get(type)
        klass.respond_to?(:openapi_one_of) ? klass.build(value) : klass.build_from_hash(value)
      end
    end

    # Returns the string representation of the object
    # @return [String] String presentation of the object
    def to_s
      to_hash.to_s
    end

    # to_body is an alias to to_hash (backward compatibility)
    # @return [Hash] Returns the object in the form of hash
    def to_body
      to_hash
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

    # Outputs non-array value in the form of hash
    # For object, use to_hash. Otherwise, just return the value
    # @param [Object] value Any valid value
    # @return [Hash] Returns the value in the form of hash
    def _to_hash(value)
      if value.is_a?(Array)
        value.compact.map { |v| _to_hash(v) }
      elsif value.is_a?(Hash)
        {}.tap do |hash|
          value.each { |k, v| hash[k] = _to_hash(v) }
        end
      elsif value.respond_to? :to_hash
        value.to_hash
      else
        value
      end
    end

  end

end
